{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  labels:
    app.kubernetes.io/name: {{ include "github-exporter.name" . }}
    helm.sh/chart: {{ include "github-exporter.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    {{- if .Values.ingress.extraLabels }}
    {{ .Values.ingress.extraLabels | toYaml | nindent 4 -}}
    {{- end }}
  {{- if .Values.ingress.annotations }}
  annotations:
  {{ .Values.ingress.annotations | toYaml | nindent 4 -}}
  {{- end }}
  name: {{ include "github-exporter.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
      - path: "/"
        pathType: Prefix
        backend:
          service:
            name: {{ include "github-exporter.name" . }}-ingress
            port:
              number: {{ .Values.service.portHttp }}
{{- end }}