apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: {{ include "github-exporter.name" . }}
    helm.sh/chart: {{ include "github-exporter.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    {{- if .Values.service.extraLabels -}}
    {{ .Values.service.extraLabels | toYaml | nindent 4 -}}
    {{- end }}
  {{- if .Values.service.annotationsMetrics }}
  annotations:
  {{ .Values.service.annotationsMetrics | toYaml | nindent 4 -}}
  {{- end }}
  name: {{ include "github-exporter.name" . }}-metrics
  namespace: {{ .Release.Namespace }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.portMetrics }}
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    app.kubernetes.io/name: {{ include "github-exporter.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
---
{{- if .Values.ingress.enabled }}
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: {{ include "github-exporter.name" . }}
    helm.sh/chart: {{ include "github-exporter.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    {{- if .Values.service.extraLabels -}}
    {{ .Values.service.extraLabels | toYaml | nindent 4 -}}
    {{- end }}
  {{- if .Values.service.annotationsIngress }}
  annotations:
  {{ .Values.service.annotationsIngress | toYaml | nindent 4 -}}
  {{- end }}
  name: {{ include "github-exporter.name" . }}-ingress
  namespace: {{ .Release.Namespace }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.portHttp }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "github-exporter.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}