FROM cgr.dev/chainguard/go:latest as builder

ARG GOARCH="amd64"
ARG GOOS="linux"

WORKDIR /code
COPY . .

RUN go build -o github-actions-exporter .

FROM cgr.dev/chainguard/static:latest

COPY --from=builder /code/github-actions-exporter /bin/github-actions-exporter

USER nobody
ENTRYPOINT ["/bin/github-actions-exporter"]
EXPOSE     9101
