FROM golang:1.17-alpine as builder

ARG GOARCH="amd64"
ARG GOOS="linux"

WORKDIR /code
COPY . .

RUN go build -o github-actions-exporter .

FROM ghcr.io/distroless/busybox:latest

COPY --from=builder /code/github-actions-exporter /bin/github-actions-exporter

USER nobody
ENTRYPOINT ["/bin/github-actions-exporter"]
EXPOSE     9101
