version: '3.8'

services:
  github-actions-exporter:
    build:
      context: ..
      dockerfile: example/Dockerfile.dev
    command:
      - "--gh.github-webhook-token=$WEBHOOK_SECRET"
      - "--gh.github-api-token=$GITHUB_TOKEN"
      - "--gh.github-org=$GITHUB_ORG"
    ports:
      - 9101:9101
    expose:
      - 9101

  prometheus:
    image: prom/prometheus:v2.54.1
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - 9090:9090
