global:
  scrape_interval:     15s

scrape_configs:
  - job_name: "prometheus"
    scrape_interval: 5s
    static_configs:
    - targets: ["localhost:9090"]

  - job_name: "github-actions-exporter"
    static_configs:
    - targets: ["github-actions-exporter:9101"]
