project_name: github_actions_exporter

env:
  - DOCKER_CLI_EXPERIMENTAL=enabled
  - COSIGN_YES=true

gomod:
  proxy: true

snapshot:
  name_template: '{{ .Tag }}-SNAPSHOT'

builds:
  - id: binary
    binary: github-actions-exporter
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
      - arm
      - s390x
      - ppc64le
    goarm:
      - 7
    ldflags: |
      -X github.com/prometheus/common/version.Version={{.Version}}
      -X github.com/prometheus/common/version.Revision={{.Commit}}
      -X github.com/prometheus/common/version.Branch={{.Branch}}
      -X github.com/prometheus/common/version.BuildUser=cpanato
      -X github.com/prometheus/common/version.BuildDate={{.Date}}

archives:
  - format: binary
    allow_different_binary_count: true

checksum:
  name_template: checksums.txt

signs:
  - signature: "${artifact}.sig"
    certificate: "${artifact}.pem"
    cmd: cosign
    args: ["sign-blob", "--output-signature", "${artifact}.sig", "--output-certificate", "${artifact}.pem", "${artifact}"]
    artifacts: binary

kos:
  - id: ko-image
    main: .
    base_image: cgr.dev/chainguard/static
    repository: ghcr.io/cpanato/{{ .ProjectName }}
    platforms:
      - all
    tags:
      - '{{ .Version }}'
    sbom: spdx
    build: binary
    bare: true
    preserve_import_paths: false
    base_import_paths: true

docker_signs:
  - artifacts: all
    args: ["sign", "${artifact}"]

release:
  github:
    owner: cpanato
    name: github_actions_exporter
  draft: false
  prerelease: allow
