project_name: github_actions_exporter
version: 2

env:
  - DOCKER_CLI_EXPERIMENTAL=enabled
  - COSIGN_YES=true

# Prevents parallel builds from stepping on each others toes downloading modules
before:
  hooks:
    - go mod tidy
    - /bin/bash -c 'if [ -n "$(git --no-pager diff --exit-code go.mod go.sum)" ]; then exit 1; fi'

gomod:
  proxy: true

snapshot:
  version_template: '{{ .Tag }}-SNAPSHOT'

builds:
  - id: binary
    binary: github-actions-exporter
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
      - arm
    goarm:
      - 7
    ldflags: |
      -X github.com/prometheus/common/version.Version={{.Version}}
      -X github.com/prometheus/common/version.Revision={{.Commit}}
      -X github.com/prometheus/common/version.Branch={{.Branch}}
      -X github.com/prometheus/common/version.BuildUser=cpanato
      -X github.com/prometheus/common/version.BuildDate={{.Date}}

archives:
  - format: binary
    allow_different_binary_count: true

checksum:
  name_template: checksums.txt

signs:
  - signature: "${artifact}.sig"
    certificate: "${artifact}.pem"
    cmd: cosign
    args: ["sign-blob", "--output-signature", "${artifact}.sig", "--output-certificate", "${artifact}.pem", "${artifact}"]
    artifacts: binary
  - id: checksum-sign
    signature: "${artifact}.sig"
    certificate: "${artifact}.pem"
    cmd: cosign
    args: ["sign-blob", "--output-signature", "${artifact}.sig", "--output-certificate", "${artifact}.pem", "${artifact}"]
    artifacts: checksum

kos:
  - id: ko-image
    main: .
    base_image: cgr.dev/chainguard/static
    repository: ghcr.io/cpanato
    platforms:
      - all
    tags:
      - 'v{{ .Version }}'
    sbom: spdx
    build: binary
    bare: true
    preserve_import_paths: false
    base_import_paths: true

release:
  github:
    owner: cpanato
    name: github_actions_exporter
  draft: false
  prerelease: allow
